name: ju_scooter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.0.2
  lottie: ^3.3.1
  firebase_core: ^3.13.0
  #cloud_firestore: ^5.6.7
  #firebase_storage: ^12.4.5
  #firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.3
 # google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  cloud_functions: ^5.5.0
  cloud_firestore: ^5.6.7
  google_maps_flutter: ^2.12.1
  geolocator: ^12.0.0
  http: ^1.4.0
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  firebase_storage: ^12.4.5
  session_manager: ^0.0.4
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5
  barcode_scan2: ^4.5.1
  #qr_code_scanner: ^1.0.1
  #flutter_dotenv: ^5.2.1
  #go_sell_sdk_flutter: ^2.4.18
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  

flutter:
  uses-material-design: true
  assets:
    - assets/email.png
    - assets/background.png
    - assets/next_button.png
    - assets/background_image.png
    - assets/background_image_2.png
    - assets/background_image_3.png
    - assets/background_image_4.png
    - assets/app_icon.png
    - assets/scooter_icon.png
    - assets/search_prefix_icon.png
    - assets/user_profile_icon.png
    - assets/user_profile_icon.png
    - assets/my_location_icon.svg
    - assets/support.svg
    - assets/icons/payment_icon.svg
    - assets/icons/guide_icon.svg
    - assets/icons/menu_icon.svg
    - assets/icons/qr.svg
    - assets/r1/bxs_videos.png
    - assets/r1/Group.png
    - assets/r1/oui_documentation.png
    - assets/r1/gis_map-route.png
    - assets/r1/scooter.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" # لون الخلفية
  adaptive_icon_foreground: "assets/app_icon.png"

analyzer:
  errors:
    prefer_final_fields: ignore